name: update

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login (ghcr)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ghcr.io/alterakey/blutter
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Check out code
        uses: actions/checkout@v6

      - name: Check out code (upstream)
        uses: actions/checkout@v6
        id: up
        with:
          path: blutter
          repository: worawit/blutter

      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: .done
          key: built-${{ github.sha }}-${{ steps.up.outputs.commit }}

      - name: Get shortrev (upstream)
        id: upshort
        run: |
          echo "rev=$(git rev-parse --short ${{ steps.up.outputs.commit }})" > "$GITHUB_OUTPUT"

      - name: Building and pushing container
        uses: docker/build-push-action@v5
        if: ${{ steps.cache.cache-hit != 'true' }}
        with:
          context: .
          push: true
          tags: |
            ghcr.io/alterakey/blutter:latest
            ghcr.io/alterakey/blutter:v${{ steps.upshort.outputs.rev }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/alterakey/blutter:buildcache
          cache-to: type=registry,ref=ghcr.io/alterakey/blutter:buildcache,mode=max

      - name: Mark as done
        if: ${{ steps.cache.cache-hit != 'true' }}
        run: |
          touch .done
